{% set version = "1.12.3" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  fn: argcomplete-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/argcomplete/argcomplete-{{ version }}.tar.gz
  md5: ded03f9c5d41c193dfe5869634d78211

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - importlib_metadata >=0.23,<4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - argcomplete

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache-2.0
  summary: Bash tab completion for argparse
  license_family: Apache
  license_file: LICENSE.rst
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
    - xylar
